-- 建立 vote-room 的本次遊戲清單資料表
CREATE TABLE IF NOT EXISTS public.vote_room_games (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name TEXT NOT NULL,
  game_url TEXT,
  game_price TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.vote_room_games
  DROP CONSTRAINT IF EXISTS vote_room_games_game_name_not_empty;
ALTER TABLE public.vote_room_games
  ADD CONSTRAINT vote_room_games_game_name_not_empty
  CHECK (char_length(btrim(game_name)) > 0);

-- 啟用 Realtime（若已加入會自動略過）
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.vote_room_games;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

COMMENT ON TABLE public.vote_room_games IS 'vote-room 當次遊戲清單';
COMMENT ON COLUMN public.vote_room_games.game_name IS '遊戲名稱';
COMMENT ON COLUMN public.vote_room_games.game_url IS '遊戲網址';
COMMENT ON COLUMN public.vote_room_games.game_price IS '價格文字，格式建議為 X人/XXXX元';
