-- 建立戶外桌遊投票資料表
CREATE TABLE IF NOT EXISTS public.outdoor_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name TEXT NOT NULL,
  voter_name TEXT NOT NULL,
  agree_vote BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 若資料表已存在，補上每日投票欄位（同姓名同遊戲每日限投 1 次）
ALTER TABLE public.outdoor_votes
  ADD COLUMN IF NOT EXISTS vote_day DATE NOT NULL DEFAULT CURRENT_DATE;

-- 防止同姓名 + 同遊戲在同一天重複投票（大小寫與前後空白視為同一值）
CREATE UNIQUE INDEX IF NOT EXISTS outdoor_votes_unique_daily_vote
  ON public.outdoor_votes (
    lower(btrim(game_name)),
    lower(btrim(voter_name)),
    vote_day
  );

-- 基本資料品質限制
ALTER TABLE public.outdoor_votes
  DROP CONSTRAINT IF EXISTS outdoor_votes_game_name_not_empty;
ALTER TABLE public.outdoor_votes
  ADD CONSTRAINT outdoor_votes_game_name_not_empty
  CHECK (char_length(btrim(game_name)) > 0);

ALTER TABLE public.outdoor_votes
  DROP CONSTRAINT IF EXISTS outdoor_votes_voter_name_not_empty;
ALTER TABLE public.outdoor_votes
  ADD CONSTRAINT outdoor_votes_voter_name_not_empty
  CHECK (char_length(btrim(voter_name)) > 0);

-- 啟用 Realtime（若已加入會自動略過）
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.outdoor_votes;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

COMMENT ON TABLE public.outdoor_votes IS '戶外桌遊投票資料';
COMMENT ON COLUMN public.outdoor_votes.game_name IS '投票的遊戲名稱';
COMMENT ON COLUMN public.outdoor_votes.voter_name IS '投票人姓名';
COMMENT ON COLUMN public.outdoor_votes.agree_vote IS '是否勾選同意投票';
COMMENT ON COLUMN public.outdoor_votes.vote_day IS '投票日期（每日唯一投票限制用）';
