-- 共用投票頁的可選遊戲清單（依 scope 區分頁面）
CREATE TABLE IF NOT EXISTS public.vote_game_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope TEXT NOT NULL,
  option_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 防止同一 scope 下重複名稱（忽略大小寫與前後空白）
CREATE UNIQUE INDEX IF NOT EXISTS vote_game_options_scope_name_unique
  ON public.vote_game_options (
    scope,
    lower(btrim(option_name))
  );

-- 基本資料品質限制
ALTER TABLE public.vote_game_options
  DROP CONSTRAINT IF EXISTS vote_game_options_scope_not_empty;
ALTER TABLE public.vote_game_options
  ADD CONSTRAINT vote_game_options_scope_not_empty
  CHECK (char_length(btrim(scope)) > 0);

ALTER TABLE public.vote_game_options
  DROP CONSTRAINT IF EXISTS vote_game_options_option_name_not_empty;
ALTER TABLE public.vote_game_options
  ADD CONSTRAINT vote_game_options_option_name_not_empty
  CHECK (char_length(btrim(option_name)) > 0);

-- 啟用 Realtime（若已加入會自動略過）
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.vote_game_options;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

COMMENT ON TABLE public.vote_game_options IS '投票頁可選遊戲清單（以 scope 區分 outdoor-vote / vote-room）';
COMMENT ON COLUMN public.vote_game_options.scope IS '頁面範圍，例如 outdoor-vote、vote-room';
COMMENT ON COLUMN public.vote_game_options.option_name IS '可選遊戲名稱';
