-- 建立密室/劇本殺投票資料表
CREATE TABLE IF NOT EXISTS public.vote_room_votes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_name TEXT NOT NULL,
  game_url TEXT,
  game_price NUMERIC(10,2),
  voter_name TEXT NOT NULL,
  agree_vote BOOLEAN NOT NULL DEFAULT true,
  vote_day DATE NOT NULL DEFAULT CURRENT_DATE,
  vote_days JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 防止同姓名 + 同遊戲在同一天重複投票（忽略大小寫與前後空白）
CREATE UNIQUE INDEX IF NOT EXISTS vote_room_votes_unique_daily_vote
  ON public.vote_room_votes (
    lower(btrim(game_name)),
    lower(btrim(voter_name)),
    vote_day
  );

-- 基本資料品質限制
ALTER TABLE public.vote_room_votes
  DROP CONSTRAINT IF EXISTS vote_room_votes_game_name_not_empty;
ALTER TABLE public.vote_room_votes
  ADD CONSTRAINT vote_room_votes_game_name_not_empty
  CHECK (char_length(btrim(game_name)) > 0);

ALTER TABLE public.vote_room_votes
  DROP CONSTRAINT IF EXISTS vote_room_votes_voter_name_not_empty;
ALTER TABLE public.vote_room_votes
  ADD CONSTRAINT vote_room_votes_voter_name_not_empty
  CHECK (char_length(btrim(voter_name)) > 0);

ALTER TABLE public.vote_room_votes
  DROP CONSTRAINT IF EXISTS vote_room_votes_game_price_non_negative;
ALTER TABLE public.vote_room_votes
  ADD CONSTRAINT vote_room_votes_game_price_non_negative
  CHECK (game_price IS NULL OR game_price >= 0);

-- 啟用 Realtime（若已加入會自動略過）
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.vote_room_votes;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

COMMENT ON TABLE public.vote_room_votes IS '密室/劇本殺投票資料';
COMMENT ON COLUMN public.vote_room_votes.game_name IS '投票的遊戲名稱';
COMMENT ON COLUMN public.vote_room_votes.game_url IS '遊戲參考網址（可選）';
COMMENT ON COLUMN public.vote_room_votes.game_price IS '遊戲價格（可選）';
COMMENT ON COLUMN public.vote_room_votes.voter_name IS '投票人姓名';
COMMENT ON COLUMN public.vote_room_votes.agree_vote IS '是否勾選同意投票';
COMMENT ON COLUMN public.vote_room_votes.vote_day IS '投票日期（每日唯一投票限制用）';
COMMENT ON COLUMN public.vote_room_votes.vote_days IS '投票可接受的多個日期（JSON 陣列）';
