-- 建立密室/劇本殺投票日期選項資料表
CREATE TABLE IF NOT EXISTS public.vote_room_date_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vote_date DATE NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.vote_room_date_options
  ADD CONSTRAINT IF NOT EXISTS vote_room_date_options_vote_date_not_null
  CHECK (vote_date IS NOT NULL);

-- 啟用 Realtime（若已加入會自動略過）
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.vote_room_date_options;
EXCEPTION
  WHEN duplicate_object THEN
    NULL;
END $$;

COMMENT ON TABLE public.vote_room_date_options IS '密室/劇本殺可投票日期選項';
COMMENT ON COLUMN public.vote_room_date_options.vote_date IS '可供選擇的投票日期';
COMMENT ON COLUMN public.vote_room_date_options.created_at IS '建立時間';
